### ISSUE TITLE
大佬，这个执行atom 最新版本的签名交易么？gaia v6.0.0

### ISSUE THREAD

**Issue by jc0803kevin** [cloverzrg/cosmos-sdk-java#2]

**Comment by cloverzrg** [comment]
6.0需要这边需要更新下proto文件

**Comment by jc0803kevin** [comment]
> 6.0需要这边需要更新下proto文件

大佬 可以加个联系方式么 vx: jc0803kevin,

**Comment by jacksoft121** [comment]
如何更新下proto文件？

**Comment by jc0803kevin** [comment]
> 如何更新下proto文件？

这位大佬，加个联系方式咯，看看是否可以一起搞一下这个

**Comment by cloverzrg** [comment]
已支持7.0，我没怎么测，自己仔细测下

**Comment by cloverzrg** [comment]
```
<dependency>
    <groupId>com.jeongen.cosmos</groupId>
    <artifactId>sdk</artifactId>
    <version>0.0.3</version>
</dependency>
```

**Comment by xuxingyin** [comment]
感谢大佬，加个vx吧：328416850

**Comment by jacksoft121** [comment]
> ```
> <dependency>
>     <groupId>com.jeongen.cosmos</groupId>
>     <artifactId>sdk</artifactId>
>     <version>0.0.3</version>
> </dependency>
> ```


感谢大佬，加个vx吧：328416850

**Comment by jacksoft121** [comment]
> > 如何更新下proto文件？
> 
> 这位大佬，加个联系方式咯，看看是否可以一起搞一下这个

加个vx吧：328416850
