### ISSUE TITLE
调用rpc返回值解析成对象时报错

### ISSUE THREAD

**Issue by jacksoft121** [cloverzrg/cosmos-sdk-java#3]
<img width="1052" alt="image" src="https://user-images.githubusercontent.com/5944846/163090290-bea040de-78fa-44a6-a652-46e53038e519.png">
<img width="732" alt="image" src="https://user-images.githubusercontent.com/5944846/163090319-8c99af82-c1d0-4dc6-9242-dab23aff315c.png">

比如调用
        QueryOuterClass.QueryAccountResponse  res = cosmosRestApiClient.queryAccount("cosmos12pyk5w4kuzh0kqyal4vlwy25hs9ejs230de592");
在
parser.merge(response.body().string(), builder);
处就报错，其它方法也是在此处报错；

**Comment by cloverzrg** [comment]
先更新到0.0.3

**Comment by cloverzrg** [comment]
我今晚看下，报错内容是什么？
