### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by jc0803kevin** [cloverzrg/cosmos-sdk-java#4]
![image](https://user-images.githubusercontent.com/16516973/192423610-40646974-bee7-42c3-94d3-c2af8c803e5b.png)

编译proto 的时候，就报错了，不能继续向下走了。

**Comment by cloverzrg** [comment]
我记得是需要本地安装一些proto的命令

**Comment by cloverzrg** [comment]
直接引用这个包的话, 不需要安装命令

**Comment by jc0803kevin** [comment]
能加个微信 请教一下么 jc0803kevin
